# Development override - not used in production
# This file is for local testing only

# Development override - not used in production

services:
  advent-hymnals-web:
    image: ghcr.io/adventhymnals/advent-hymnals-web:latest
    ports:
      - "3000:3000"  # Development port
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_GA_ID=G-JPQZVQ70L9  # Development GA ID
      - SITE_URL=http://localhost:3000
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
    volumes:
      - ./dev-data:/app/data
    profiles:
      - dev