# Docker Compose configuration for Advent Hymnals with Traefik

services:
  # Advent Hymnals Web Application
  advent-hymnals-web:
    image: ${ADVENT_HYMNALS_IMAGE:-ghcr.io/adventhymnals/advent-hymnals-web:latest}
    container_name: advent-hymnals-web
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}
      - SITE_URL=https://${DOMAIN}
      - NEXT_PUBLIC_SITE_URL=https://${DOMAIN}
      - GOOGLE_VERIFICATION=${GOOGLE_VERIFICATION}
      - YANDEX_VERIFICATION=${YANDEX_VERIFICATION}
    volumes:
      - hymnal-data:/app/data
      - ./logs/app:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - advent-hymnals-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      # HTTPS router
      - "traefik.http.routers.advent-hymnals.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.advent-hymnals.entrypoints=websecure"
      - "traefik.http.routers.advent-hymnals.tls=true"
      - "traefik.http.routers.advent-hymnals.tls.certresolver=letsencrypt"
      - "traefik.http.routers.advent-hymnals.service=advent-hymnals"
      - "traefik.http.services.advent-hymnals.loadbalancer.server.port=3000"
      # HTTP router (redirects to HTTPS)
      - "traefik.http.routers.advent-hymnals-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.advent-hymnals-http.entrypoints=web"
      - "traefik.http.routers.advent-hymnals-http.middlewares=redirect-to-https"
      # Redirect middleware
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

  # Media Server for serving hymnal files
  media-server:
    image: ${MEDIA_SERVER_IMAGE:-ghcr.io/adventhymnals/media-server:latest}
    container_name: advent-hymnals-media
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MEDIA_PATH=/media
      - CORS_ORIGIN=https://${DOMAIN}
    volumes:
      - media-files:/media:ro
      - ./logs/media:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - advent-hymnals-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      # HTTPS router for media subdomain (media.gospelsounders.org)
      - "traefik.http.routers.advent-media.rule=Host(`media.${DOMAIN}`)"
      - "traefik.http.routers.advent-media.entrypoints=websecure"
      - "traefik.http.routers.advent-media.tls=true"
      - "traefik.http.routers.advent-media.tls.certresolver=letsencrypt"
      - "traefik.http.routers.advent-media.service=advent-media"
      - "traefik.http.services.advent-media.loadbalancer.server.port=4000"
      # HTTP router for subdomain (redirects to HTTPS)
      - "traefik.http.routers.advent-media-http.rule=Host(`media.${DOMAIN}`)"
      - "traefik.http.routers.advent-media-http.entrypoints=web"
      - "traefik.http.routers.advent-media-http.middlewares=redirect-to-https"
      # HTTPS router for path-based access (gospelsounders.org/media)
      - "traefik.http.routers.advent-media-path.rule=Host(`${DOMAIN}`) && PathPrefix(`/media`)"
      - "traefik.http.routers.advent-media-path.entrypoints=websecure"
      - "traefik.http.routers.advent-media-path.tls=true"
      - "traefik.http.routers.advent-media-path.tls.certresolver=letsencrypt"
      - "traefik.http.routers.advent-media-path.service=advent-media"
      - "traefik.http.routers.advent-media-path.middlewares=media-strip-prefix,cors-headers"
      # HTTP router for path-based access (redirects to HTTPS)
      - "traefik.http.routers.advent-media-path-http.rule=Host(`${DOMAIN}`) && PathPrefix(`/media`)"
      - "traefik.http.routers.advent-media-path-http.entrypoints=web"
      - "traefik.http.routers.advent-media-path-http.middlewares=redirect-to-https"
      # Middleware to strip /media prefix for path-based routing
      - "traefik.http.middlewares.media-strip-prefix.stripprefix.prefixes=/media"
      # CORS headers middleware
      - "traefik.http.routers.advent-media.middlewares=cors-headers"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowmethods=GET,OPTIONS,POST"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolalloworigin=https://${DOMAIN}"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors-headers.headers.addvaryheader=true"

volumes:
  # Hymnal data volume - bind mount to host
  hymnal-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./data}
  
  # Media files volume - bind mount to host
  media-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MEDIA_PATH:-./data/sources}
  
  # Traefik Let's Encrypt certificates
  traefik-letsencrypt:
    driver: local

networks:
  # Internal network for services communication
  advent-hymnals-network:
    driver: bridge
    internal: true
  
  # External network for Traefik
  proxy-network:
    driver: bridge
    external: true
