version: '3.8'

services:
  advent-hymnals-web:
    image: ghcr.io/adventhymnals/advent-hymnals-web:latest
    container_name: advent-hymnals-web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}
      - SITE_URL=${SITE_URL:-https://adventhymnals.org}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-https://adventhymnals.org}
      - GOOGLE_VERIFICATION=${GOOGLE_VERIFICATION}
      - YANDEX_VERIFICATION=${YANDEX_VERIFICATION}
    volumes:
      - hymnal-data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - advent-hymnals-network
    labels:
      - "com.docker.compose.project=advent-hymnals"
      - "com.docker.compose.service=web"

  nginx:
    image: nginx:alpine
    container_name: advent-hymnals-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
      - certbot-web:/var/www/certbot
      - certbot-certs:/etc/letsencrypt
    depends_on:
      - advent-hymnals-web
    restart: unless-stopped
    networks:
      - advent-hymnals-network
      - web-network
    labels:
      - "com.docker.compose.project=advent-hymnals"
      - "com.docker.compose.service=nginx"

  certbot:
    image: certbot/certbot
    container_name: advent-hymnals-certbot
    volumes:
      - certbot-web:/var/www/certbot
      - certbot-certs:/etc/letsencrypt
      - ./logs/certbot:/var/log/letsencrypt
    command: >
      sh -c "while :; do
        certbot renew --webroot --webroot-path=/var/www/certbot --quiet
        sleep 12h
      done"
    restart: unless-stopped
    networks:
      - advent-hymnals-network
    labels:
      - "com.docker.compose.project=advent-hymnals"
      - "com.docker.compose.service=certbot"

volumes:
  hymnal-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  certbot-web:
  certbot-certs:

networks:
  advent-hymnals-network:
    driver: bridge
  web-network:
    external: true